# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1_cnn_npu/design_1_cnn_npu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu || ORIG_REF_NAME==design_1_cnn_npu} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_processing_system7_0_0/design_1_cnn_npu_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_processing_system7_0_0 || ORIG_REF_NAME==design_1_cnn_npu_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_proc_sys_reset_0_1/design_1_cnn_npu_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_axi_interconnect_0_imp_xbar_0/design_1_cnn_npu_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==design_1_cnn_npu_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_axi_interconnect_0_0/design_1_cnn_npu_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_cnn_npu_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_myip_cnn_classificat_0_0/design_1_cnn_npu_myip_cnn_classificat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_myip_cnn_classificat_0_0 || ORIG_REF_NAME==design_1_cnn_npu_myip_cnn_classificat_0_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_myip_cnn_uart_cntr_0_0/design_1_cnn_npu_myip_cnn_uart_cntr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_myip_cnn_uart_cntr_0_0 || ORIG_REF_NAME==design_1_cnn_npu_myip_cnn_uart_cntr_0_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_myip_uart_rxtx_0_0/design_1_cnn_npu_myip_uart_rxtx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_myip_uart_rxtx_0_0 || ORIG_REF_NAME==design_1_cnn_npu_myip_uart_rxtx_0_0} -quiet] -quiet

# IP: bd/design_1_cnn_npu/ip/design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0/design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/ming/workspace_ondevice_2/Project_NPU/wafer_npu/wafer_npu.gen/sources_1/bd/design_1_cnn_npu/ip/design_1_cnn_npu_processing_system7_0_0/design_1_cnn_npu_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_processing_system7_0_0 || ORIG_REF_NAME==design_1_cnn_npu_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ming/workspace_ondevice_2/Project_NPU/wafer_npu/wafer_npu.gen/sources_1/bd/design_1_cnn_npu/ip/design_1_cnn_npu_proc_sys_reset_0_1/design_1_cnn_npu_proc_sys_reset_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ming/workspace_ondevice_2/Project_NPU/wafer_npu/wafer_npu.gen/sources_1/bd/design_1_cnn_npu/ip/design_1_cnn_npu_proc_sys_reset_0_1/design_1_cnn_npu_proc_sys_reset_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_cnn_npu_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ming/workspace_ondevice_2/Project_NPU/wafer_npu/wafer_npu.gen/sources_1/bd/design_1_cnn_npu/ip/design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0/design_1_cnn_npu_axi_interconnect_0_imp_auto_pc_0_ooc.xdc

# XDC: /home/ming/workspace_ondevice_2/Project_NPU/wafer_npu/wafer_npu.gen/sources_1/bd/design_1_cnn_npu/design_1_cnn_npu_ooc.xdc
